[package]
name = "music_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
dotenv = "0.15.0"
kdl = "6.3.2"
poise = "0.6.1"
reqwest = "0.11.27"
songbird = { version = "0.4.6", features = ["driver"] }
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
